### PR TITLE
chore: Add dependabot for automatic dependency version bump

### LINKED ISSUE #299: Ajout d'un outil pour proposer des mises à jour
# Besoin

Le projet est un projet interne sur lequel des personnes vont travailler sur des périodes courtes (intercontrat). Pourtant il faut pouvoir maintenir à jour les dépendances de ce projet.

# Solution

Ajouter un outil tel que Renovate afin proposer les mises à jour des dépendances.

### PR DESCRIPTION
**Pull request by bessonm**
fix #299

@lisequesnel you suggested using Renovate, I have no preference and this is up for debate.
GitHub provides built-in integration with Dependabot, here is a simple setup configuration.

### CODE REVIEW

**Comment by lisequesnel** [comment]
> @lisequesnel you suggested using Renovate, I have no preference and this is up for debate. GitHub provides built-in integration with Dependabot, here is a simple setup configuration.

I know Renovate better, but I am open to Dependabot

**Comment by jeanphibaconnais** [comment]
@lisequesnel I checked this PR and this is a good configuration to start with dependabot 😄

**Comment by avine** [comment]
Pierre Nicoli said to me that Zenika don't have GitHub actions plan.

**Comment by avine** [comment]
Dependabot wil only update dependencies according to `package.json` ?
So, we still need a manual action to upgrade major versions, let say from Angular 17 to Angular 18.
Is it correct ?

**Comment by jeanphibaconnais** [comment]
> Dependabot wil only update dependencies according to `package.json` ? So, we still need a manual action to upgrade major versions, let say from Angular 17 to Angular 18. Is it correct ?

Yes that's true. Dependabot can be configured to automerge but it's recommended to merge manually the major version.

**Comment by bessonm** [comment]
> > Dependabot wil only update dependencies according to `package.json` ? So, we still need a manual action to upgrade major versions, let say from Angular 17 to Angular 18. Is it correct ?
> 
> Yes that's true. Dependabot can be configured to automerge but it's recommended to merge manually the major version.

Yes, this config limit to 10 PRs per week and do not automerge anything.
And if you dismiss a PR it wont re-open it again for the same version bump.

The idea is to help being up-to-date without being overwhelmed, and keeping a bit of control since the project does not have many contributors working on it on daily basis.

**Comment by avine** [comment]
But is this requires a GitHub Actions plan ? Because we don't (and will not) have one at Zenika (as I heard from Pierre).

**Comment by bessonm** [comment]
> But is this requires a GitHub Actions plan ? Because we don't (and will not) have one at Zenika (as I heard from Pierre).

Not to my knowledge and I can't find anything related to "Action plan" in there doc, so it should be free  :
- https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuring-dependabot-version-updates

**Pull request merged**
